---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
games <- CodeClanData::game_sales
library(DT)
```

For this analysis I have decided to look at games sales from the past 20 years(1996-2016).

```{r}

crossplatform_games <- games %>% group_by(name) %>% filter(n_distinct(platform) > 1)
singleplatform_games <- games %>%  group_by(name) %>% filter(n_distinct(platform) == 1)

```

I was wondering what were the top 5 games platforms by sales in a chosen year.

```{r}

games %>% filter(year_of_release == 2007) %>% group_by(platform) %>% summarise(total_sales = sum(sales)) %>% head(n = 5) %>% 
  ggplot()+
  aes(x = total_sales, y = platform)+
  geom_col(fill = "navyblue")+
   geom_text(aes(label = ifelse(total_sales>1, total_sales, " ")),
            colour = "white", size = 5, hjust = 1.3
    
  )+
  labs(
    title = "\nTop 5 Game Platforms by Sales in the chosen Year\n",
    x = "\nTotal Sales (mln)\n", 
    y = "\nPlatform\n"
  )+
  theme(
    text = element_text(size = 12),
    title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 10),
    panel.background = element_rect((fill = "white")),
    panel.grid = element_line(colour = "grey", linetype = "dotted")
  )
  

```
 
 I was also curious what were the top 5 most best selling genres in the specific year.
 

```{r}
games %>%  filter(year_of_release == 2011) %>% group_by(genre, publisher) %>% summarise(total_sales = sum(sales)) %>% arrange(desc(total_sales)) 

games %>%  filter(year_of_release == 2011) %>% group_by(genre) %>% summarise(total_sales = sum(sales)) %>% arrange(desc(total_sales)) %>% head(n = 5) %>% 
  ggplot()+
  aes(x = total_sales, y = genre)+
  geom_col(fill = "navy")+
   geom_text(aes(label = ifelse(total_sales > 1, total_sales, " ")),
            colour = "white", size = 5, hjust = 1.2)+
  labs(
    title = "\nTop 5 Game Genres by Sales in the chosen Year\n",
    x = "\nTotal Sales (mln)\n", 
    y = "\nGenre\n"
  )+
  theme(
    text = element_text(size = 12),
    title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 10),
    panel.background = element_rect((fill = "white")),
    panel.grid = element_line(colour = "grey", linetype = "dotted")
  )
  
```


```{r}
games %>% filter(between(year_of_release, 1996, 2016)) %>% group_by(year_of_release) %>% summarise(total_sales = sum(sales)) %>% 
ggplot()+
  aes(x = year_of_release, y = total_sales)+
  geom_line(size = 1.5, colour = "navy")+
  labs(
    title = "\n Game Sales from 1988 to 2016\n",
    x = "\nYear\n", 
    y = "\nSales (mln)\n"
  )+
  theme(
    text = element_text(size = 12),
    title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 10),
    panel.background = element_rect((fill = "white")),
    panel.grid = element_line(colour = "grey", linetype = "dotted")
  )

```

Top selling games by publisher 
Top selling games by platform
Top selling games by genre





















